/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ShapeDatumWhereInput } from "./ShapeDatumWhereInput";
import { Type } from "class-transformer";
import { ShapeDatumOrderByInput } from "./ShapeDatumOrderByInput";

@ArgsType()
class ShapeDatumFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => ShapeDatumWhereInput,
  })
  @Field(() => ShapeDatumWhereInput, { nullable: true })
  @Type(() => ShapeDatumWhereInput)
  where?: ShapeDatumWhereInput;

  @ApiProperty({
    required: false,
    type: ShapeDatumOrderByInput,
  })
  @Field(() => ShapeDatumOrderByInput, { nullable: true })
  @Type(() => ShapeDatumOrderByInput)
  orderBy?: ShapeDatumOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { ShapeDatumFindManyArgs };
