/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateShapeDatumArgs } from "./CreateShapeDatumArgs";
import { UpdateShapeDatumArgs } from "./UpdateShapeDatumArgs";
import { DeleteShapeDatumArgs } from "./DeleteShapeDatumArgs";
import { ShapeDatumFindManyArgs } from "./ShapeDatumFindManyArgs";
import { ShapeDatumFindUniqueArgs } from "./ShapeDatumFindUniqueArgs";
import { ShapeDatum } from "./ShapeDatum";
import { ShapeDatumService } from "../shapeDatum.service";

@graphql.Resolver(() => ShapeDatum)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ShapeDatumResolverBase {
  constructor(
    protected readonly service: ShapeDatumService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "read",
    possession: "any",
  })
  async _shapeDataMeta(
    @graphql.Args() args: ShapeDatumFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ShapeDatum])
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "read",
    possession: "any",
  })
  async shapeData(
    @graphql.Args() args: ShapeDatumFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ShapeDatum[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ShapeDatum",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ShapeDatum, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "read",
    possession: "own",
  })
  async shapeDatum(
    @graphql.Args() args: ShapeDatumFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ShapeDatum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ShapeDatum",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ShapeDatum)
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "create",
    possession: "any",
  })
  async createShapeDatum(
    @graphql.Args() args: CreateShapeDatumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ShapeDatum> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ShapeDatum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ShapeDatum"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ShapeDatum)
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "update",
    possession: "any",
  })
  async updateShapeDatum(
    @graphql.Args() args: UpdateShapeDatumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ShapeDatum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ShapeDatum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ShapeDatum"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ShapeDatum)
  @nestAccessControl.UseRoles({
    resource: "ShapeDatum",
    action: "delete",
    possession: "any",
  })
  async deleteShapeDatum(
    @graphql.Args() args: DeleteShapeDatumArgs
  ): Promise<ShapeDatum | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
